[project]
name = "backblaze"
version = "0.1.0"
description = "Multimodal Data Processing with Pixeltable and Backblaze B2"
requires-python = ">=3.10"
dependencies = [
    "pixeltable>=0.4.24",
]

[dependency-groups]
dev = [
    "jupyter",
    "ipykernel",
]

